ignoredBuiltDependencies:
  - '@apollo/protobufjs'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - cypress
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - prisma
  - 'libs/*'
  - 'apps/*'
